/**
 * DHCP option code reference data, adapted from the IANA BOOTP/DHCP parameters
 * registry and Ingmar Verheij's "Read DHCP options received by the client" script:
 * https://www.ingmarverheij.com/read-dhcp-options-received-by-the-client/
 */

export type DhcpOptionValueType = "ip" | "string" | "time" | "dhcpmsgtype";

export interface DhcpOptionMeta {
  name: string;
  type?: DhcpOptionValueType;
}

export const DHCP_OPTIONS: Record<number, DhcpOptionMeta> = {
  0: { name: "Pad" },
  1: { name: "Subnet Mask", type: "ip" },
  2: { name: "Time Offset", type: "time" },
  3: { name: "Router", type: "ip" },
  4: { name: "Time Server", type: "ip" },
  5: { name: "Name Server", type: "string" },
  6: { name: "Domain Server (DNS)", type: "ip" },
  7: { name: "Log Server" },
  8: { name: "Quotes Server" },
  9: { name: "LPR Server" },
  10: { name: "Impress Server" },
  11: { name: "RLP Server" },
  12: { name: "Hostname", type: "string" },
  13: { name: "Boot File Size" },
  14: { name: "Merit Dump File" },
  15: { name: "Domain Name", type: "string" },
  16: { name: "Swap Server" },
  17: { name: "Root Path" },
  18: { name: "Extension File" },
  19: { name: "Forward On/Off" },
  20: { name: "SrcRte On/Off" },
  21: { name: "Policy Filter" },
  22: { name: "Max DG Assembly" },
  23: { name: "Default IP TTL" },
  24: { name: "MTU Timeout" },
  25: { name: "MTU Plateau" },
  26: { name: "MTU Interface" },
  27: { name: "MTU Subnet" },
  28: { name: "Broadcast Address" },
  29: { name: "Mask Discovery" },
  30: { name: "Mask Supplier" },
  31: { name: "Router Discovery" },
  32: { name: "Router Request" },
  33: { name: "Static Route" },
  34: { name: "Trailers" },
  35: { name: "ARP Timeout" },
  36: { name: "Ethernet" },
  37: { name: "Default TCP TTL" },
  38: { name: "Keepalive Time" },
  39: { name: "Keepalive Data" },
  40: { name: "NIS Domain" },
  41: { name: "NIS Servers" },
  42: { name: "NTP Servers" },
  43: { name: "Vendor Specific" },
  44: { name: "NETBIOS Name Srv" },
  45: { name: "NETBIOS Dist Srv" },
  46: { name: "NETBIOS Node Type" },
  47: { name: "NETBIOS Scope" },
  48: { name: "X Window Font" },
  49: { name: "X Window Manager" },
  50: { name: "Address Request" },
  51: { name: "Address Time (Lease Time)", type: "time" },
  52: { name: "Overload" },
  53: { name: "DHCP Message Type", type: "dhcpmsgtype" },
  54: { name: "DHCP Server Id", type: "ip" },
  55: { name: "Parameter Request List" },
  56: { name: "DHCP Message" },
  57: { name: "DHCP Max Msg Size" },
  58: { name: "Renewal Time (T1)", type: "time" },
  59: { name: "Rebinding Time (T2)", type: "time" },
  60: { name: "Class Id" },
  61: { name: "Client Id" },
  62: { name: "NetWare/IP Domain" },
  63: { name: "NetWare/IP Option" },
  64: { name: "NIS-Domain-Name" },
  65: { name: "NIS-Server-Addr" },
  66: { name: "Server-Name (TFTP/Next-Server)", type: "string" },
  67: { name: "Bootfile-Name", type: "string" },
  68: { name: "Home-Agent-Addrs" },
  69: { name: "SMTP-Server" },
  70: { name: "POP3-Server" },
  71: { name: "NNTP-Server" },
  72: { name: "WWW-Server" },
  73: { name: "Finger-Server" },
  74: { name: "IRC-Server" },
  75: { name: "StreetTalk-Server" },
  76: { name: "STDA-Server" },
  77: { name: "User-Class" },
  78: { name: "Directory Agent" },
  79: { name: "Service Scope" },
  80: { name: "Rapid Commit" },
  81: { name: "Client FQDN" },
  82: { name: "Relay Agent Information" },
  83: { name: "iSNS" },
  84: { name: "REMOVED/Unassigned" },
  85: { name: "NDS Servers" },
  86: { name: "NDS Tree Name" },
  87: { name: "NDS Context" },
  88: { name: "BCMCS Controller Domain Name list" },
  89: { name: "BCMCS Controller IPv4 address option" },
  90: { name: "Authentication" },
  91: { name: "client-last-transaction-time option" },
  92: { name: "associated-ip option" },
  93: { name: "Client System" },
  94: { name: "Client NDI" },
  95: { name: "LDAP" },
  96: { name: "REMOVED/Unassigned" },
  97: { name: "UUID/GUID" },
  98: { name: "User-Auth" },
  99: { name: "GEOCONF_CIVIC" },
  100: { name: "PCode (POSIX Timezone)", type: "string" },
  101: { name: "TCode (TZ Database Name)", type: "string" },
  108: { name: "REMOVED/Unassigned" },
  109: { name: "Unassigned" },
  110: { name: "REMOVED/Unassigned" },
  111: { name: "Unassigned" },
  112: { name: "Netinfo Address" },
  113: { name: "Netinfo Tag" },
  114: { name: "URL" },
  115: { name: "REMOVED/Unassigned" },
  116: { name: "Auto-Config" },
  117: { name: "Name Service Search" },
  118: { name: "Subnet Selection Option" },
  119: { name: "Domain Search", type: "string" },
  120: { name: "SIP Servers DHCP Option" },
  121: { name: "Classless Static Route Option" },
  122: { name: "CCC" },
  123: { name: "GeoConf Option" },
  124: { name: "V-I Vendor Class" },
  125: { name: "V-I Vendor-Specific Information" },
  126: { name: "Removed/Unassigned" },
  127: { name: "Removed/Unassigned" },
  128: { name: "PXE - undefined (vendor specific)" },
  129: { name: "PXE - undefined (vendor specific)" },
  130: { name: "PXE - undefined (vendor specific)" },
  131: { name: "PXE - undefined (vendor specific)" },
  132: { name: "PXE - undefined / IEEE 802.1Q VLAN ID (vendor specific)" },
  133: { name: "PXE - undefined / IEEE 802.1D/p Layer 2 Priority (vendor specific)" },
  134: { name: "PXE - undefined / DSCP (vendor specific)" },
  135: { name: "PXE - undefined / HTTP Proxy (vendor specific)" },
  136: { name: "OPTION_PANA_AGENT" },
  137: { name: "OPTION_V4_LOST" },
  138: { name: "OPTION_CAPWAP_AC_V4" },
  139: { name: "OPTION-IPv4_Address-MoS" },
  140: { name: "OPTION-IPv4_FQDN-MoS" },
  141: { name: "SIP UA Configuration Service Domains" },
  142: { name: "OPTION-IPv4_Address-ANDSF" },
  143: { name: "OPTION-IPv6_Address-ANDSF" },
  144: { name: "GeoLoc" },
  145: { name: "FORCERENEW_NONCE_CAPABLE" },
  146: { name: "RDNSS Selection" },
  150: { name: "TFTP server address / Etherboot / GRUB config path" },
  151: { name: "status-code" },
  152: { name: "base-time" },
  153: { name: "start-time-of-state" },
  154: { name: "query-start-time" },
  155: { name: "query-end-time" },
  156: { name: "dhcp-state" },
  157: { name: "data-source" },
  175: { name: "Etherboot (tentatively assigned)" },
  176: { name: "IP Telephone (tentatively assigned)" },
  177: { name: "Etherboot / PacketCable and CableHome (replaced by 122)" },
  208: { name: "PXELINUX Magic" },
  209: { name: "Configuration File" },
  210: { name: "Path Prefix" },
  211: { name: "Reboot Time" },
  212: { name: "OPTION_6RD" },
  213: { name: "OPTION_V4_ACCESS_DOMAIN" },
  220: { name: "Subnet Allocation Option" },
  221: { name: "Virtual Subnet Selection (VSS) Option" },
  235: { name: "Microsoft Connected Cache server (DOCacheHost)", type: "string" },
  252: { name: "Private/Proxy autodiscovery (WPAD)", type: "string" },
};

/** Vendor-specific (Microsoft) suboptions, keyed by option 43 enterprise code. */
export const DHCP_VENDOR_SPECIFIC_OPTIONS: Record<number, DhcpOptionMeta> = {
  10: { name: "Windows 2000 option 1", type: "string" },
  11: { name: "Windows 2000 option 2", type: "string" },
  12: { name: "Windows 2000 option 3", type: "string" },
  212: { name: "RES Workspace Manager", type: "string" },
  220: { name: "NAP-SoH", type: "string" },
  235: { name: "Microsoft Connected Cache server (DOCacheHost)", type: "string" },
};

/** DHCP Message Type (option 53) values, index = value. */
export const DHCP_MESSAGE_TYPES: string[] = [
  "",
  "DHCPDISCOVER",
  "DHCPOFFER",
  "DHCPREQUEST",
  "DHCPDECLINE",
  "DHCPACK",
  "DHCPNAK",
  "DHCPRELEASE",
  "DHCPINFORM",
  "DHCPFORCERENEW",
  "DHCPLEASEQUERY",
  "DHCPLEASEUNASSIGNED",
  "DHCPLEASEUNKNOWN",
  "DHCPLEASEACTIVE",
  "DHCPBULKLEASEQUERY",
  "DHCPLEASEQUERYDONE",
];
